preload = ~/.config/resources/wallpapers/wallpaper2.jpg
preload = ~/.config/resources/wallpapers/wallpaper1.jpg
wallpaper = HDMI-A-1,~/.config/resources/wallpapers/wallpaper1.jpg
wallpaper = DVI-D-1,~/.config/resources/wallpapers/wallpaper2.jpg

