[colors]
background = #141729
background-alt = #4341b5
secondary = #e60053
alert = #bd2c40
foreground-alt = #525252


[bar/example]
monitor = ${env:MONITOR:}

padding-left = 0
padding-right = 2
background = #141729
font-0 = "JetBrains Mono Nerd Font:size=9;3"
bottom = true
height = 20

modules-left = xworkspaces
modules-center = date
modules-right = pulseaudio xkeyboard memory cpu

module-margin-left = 1
module-margin-right = 2



;НАСТРОЙКИ ТРЕЯ, ВЫРАВНИВАНИЕ, ОТСТУПЫ, ЕСЛИ ЗАКОМЕНТИТЬ ТО ЕГО НЕ БУДЕТ
tray-position = right
tray-padding = 2

;НАСТРОЙКА КЛАВИШЬ МЫШИ, СОВЕТУЮ ОСТАВИТЬ КАК ЕСТЬ
cursor-click = pointer
cursor-scroll = ns-resize

[module/xkeyboard]
type = internal/xkeyboard
;БЛОКИРОВКА ОТОБРАЖЕНИЯ ОПОВЕЩЕНИЯ ВКЛЮЧЕНИЯ NUM LOCK,
;ОСТАЛЬНЫЕ ОПОВЕЩЕНИЯ МОЖНО БЛОКИРОВАТЬ ЧЕРЕЗ BLACKLIST-N
blacklist-0 = num lock


;ФОРМАТ ОТОБРАЖЕНИЯ
label-layout = %layout%
label-layout-underline = ${colors.secondary}

;ОТСТУПЫ, ЦВЕТА
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
label-active-foreground = #ffffff
label-active-background = #3f3f3f
label-active-underline = #fba922
label-active-padding = 2

label-occupied = %name%
label-occupied-underline = #555555
label-occupied-padding = 2

label-urgent = %name%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-underline = #9b0a20
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = #55
label-empty-padding = 2


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU: "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM: "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%


[module/date]
type = internal/date
interval = 5

time = %H:%M
date = "%d.%m.%Y"

label = %time% | %date% 

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume = %percentage%%
label-volume-foreground = ${root.foreground}

label-muted =  muted
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}


;НАСТРОЙКИ КОМОЗИТА, ТАК КАК ЮЗАЮ PICOM НИЧЕГО ЗА НИХ НЕ СКАЖУ
[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false